app_name: tonic_mongo
env: production

sentry:
  enabled: True
  dsn: http://abc:xyz@example.com/1

kafka:
  enabled: True
  brokers:
    - 127.0.0.1:9092

statsd:
  enabled: True
  host: 10.47.124.81
  port: 8125

redis:
  enabled: True
  host: 127.0.0.1
  port: 16379

logging:
  formatters:
    - name: plain
      format: text
      color: false
  handlers:
    - name: console
      handle: console
      formatter: plain
    - name: kafka
      handle: kafka
      formatter: plain
  loggers:
    - name: default
      handlers: [console]
      level: DEBUG
    - name: topic
      handlers: [console, kafka]
      level: DEBUG
